Restuarant_Management_System_IDP/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using Restuarant_Management_System_IDP.Data;
using Restuarant_Management_System_IDP.Models;
using Restuarant_Management_System_IDP.Models.ViewModels;
using Restuarant_Management_System_IDP.Repository.IRepository;

namespace Restuarant_Management_System_IDP.Controllers
{
    [Authorize(Roles = SD.Admin)]
    public class AdminController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        //private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public AdminController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            //_signInManager = signInManager;
            _roleManager = roleManager;
        }

        public IActionResult Dashboard()
        {
            var adminDashboardVM = new AdminDashboardViewModel();
            ViewData["Message"] = TempData["Message"] as String;
            getMetrics(adminDashboardVM);
            return View(adminDashboardVM);
        }

        private void getMetrics(AdminDashboardViewModel adminDashboardVM)
        {
            adminDashboardVM.OrdersSubmitted = _unitOfWork.OrderHeader.GetAll(x => x.Status == SD.StatusSubmitted).Count();
            adminDashboardVM.OrdersonDelivery = _unitOfWork.OrderHeader.GetAll(x => x.Status == SD.StatusReady).Count();
            adminDashboardVM.OrdersCompleted = _unitOfWork.OrderHeader.GetAll(x => x.Status == SD.StatusDelivered).Count();
            adminDashboardVM.UsersRegistered = _userManager.GetUsersInRoleAsync(SD.Customer).Result.Count;
            adminDashboardVM.EmployeesRegistered = _userManager.Users.Count() - adminDashboardVM.UsersRegistered;
            adminDashboardVM.TotalSales = _unitOfWork.OrderHeader.GetAll().Sum(x => x.OrderTotal);
        }


        public async Task<IActionResult> GetUsers()
        {
            List<ApplicationUser> applicationUsers = _userManager.Users.ToList();
            List<UserViewModel> userViewModels = new List<UserViewModel>();
            string adminUserId = _userManager.GetUserId(User);

            foreach (var user in applicationUsers)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                if(adminUserId == user.Id)
                {
                    continue;
                }
                var userisLocked = user.LockoutEnd.HasValue && user.LockoutEnd.Value > DateTimeOffset.UtcNow;

                UserViewModel userViewModel = new UserViewModel()
                {
                    UserId = user.Id,
                    Name = user.FullName,
                    Email = user.Email,
                    PhoneNumber = user.PhoneNumber,
                    Role = userRoles.FirstOrDefault(),
                    isLocked = userisLocked
                };
                userViewModels.Add(userViewModel);
            }

            return View(userViewModels);
        }

        public async Task<IActionResult> LockUnlock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            if (user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
            {
                //user is currently locked, we will unlock them
                user.LockoutEnd = DateTime.Now;
            }
            else
            {
                user.LockoutEnd = DateTime.Now.AddYears(100);
            }
            await _userManager.UpdateAsync(user);
            return RedirectToAction(nameof(GetUsers));
        }


    }
}

Restuarant_Management_System_IDP/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NuGet.ProjectModel;
using Restuarant_Management_System_IDP.Models;
using Restuarant_Management_System_IDP.Models.ViewModels;
using Restuarant_Management_System_IDP.Repository.IRepository;

namespace Restuarant_Management_System_IDP.Controllers
{
    [Authorize(Roles = SD.Customer)]
    public class CustomerController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;


        public CustomerController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;

        }

        public IActionResult Index()
        {
            return View();
        }


        public IActionResult AddToCart(int id) 
        {
            string UserId = _userManager.GetUserId(User);
            ShoppingCart? cartItem = _unitOfWork.ShoppingCart.Get(c => c.ApplicationUserId == UserId && c.MenuItemId == id);

            if (cartItem == null)
            {
                cartItem = new ShoppingCart()
                {
                    ApplicationUserId = UserId,
                    MenuItemId = id,
                    Count = 1
                };
                _unitOfWork.ShoppingCart.Add(cartItem);
            }
            else
            {
                cartItem.Count += 1;
                _unitOfWork.ShoppingCart.Update(cartItem);
            }

            _unitOfWork.Save();
            return RedirectToAction("Cart");
        }

        public IActionResult Cart()
        {
            //List<ShoppingCart> cartItems = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == _userManager.GetUserId(User), includeProperties: "MenuItem").ToList();
            OrderDetailsCart orderDetailsCart = new OrderDetailsCart()
            {
                OrderHeader = new OrderHeader(),
                cartList = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == _userManager.GetUserId(User), includeProperties: "MenuItem").ToList(),
            };

            foreach (ShoppingCart cartItem in orderDetailsCart.cartList)
            {
                cartItem.MenuItem = _unitOfWork.MenuItem.Get(m => m.Id == cartItem.MenuItemId, includeProperties: "Category,SubCategory");
                orderDetailsCart.OrderHeader.OrderTotal += (cartItem.MenuItem.Price * cartItem.Count);
            }
            HttpContext.Session.SetString(SD.ShoppingCartCount, orderDetailsCart.cartList.Count.ToString());

            return View(orderDetailsCart);
        }

        public IActionResult Additem(int id)
        {
            ShoppingCart cartItem = _unitOfWork.ShoppingCart.Get(c => c.ApplicationUserId == _userManager.GetUserId(User) && c.MenuItemId == id);
            cartItem.Count += 1;
            _unitOfWork.ShoppingCart.Update(cartItem);
            _unitOfWork.Save();
            return RedirectToAction("Cart");
        }

        public IActionResult Subtractitem(int id)
        {
            ShoppingCart cartItem = _unitOfWork.ShoppingCart.Get(c => c.ApplicationUserId == _userManager.GetUserId(User) && c.MenuItemId == id);
            if (cartItem.Count == 1)
            {
                _unitOfWork.ShoppingCart.Delete(cartItem);
            }
            else
            {
                cartItem.Count -= 1;
                _unitOfWork.ShoppingCart.Update(cartItem);
            }
            _unitOfWork.Save();
            return RedirectToAction("Cart");
        }

        public IActionResult Deleteitem(int id)
        {
            ShoppingCart cartItem = _unitOfWork.ShoppingCart.Get(c => c.ApplicationUserId == _userManager.GetUserId(User) && c.MenuItemId == id);

            //delete the item from the cart
            _unitOfWork.ShoppingCart.Delete(cartItem);
            _unitOfWork.Save();

            return RedirectToAction("Cart");
        }

        public IActionResult Summary()
        {

            ApplicationUser applicationUser = _userManager.GetUserAsync(User).Result;
            string userId = _userManager.GetUserId(User);

            SummaryViewModel summaryViewModel = new SummaryViewModel()
            {
                OrderHeader = new OrderHeader(),
                Address = _unitOfWork.Addresstb.Get(u => u.UserId == userId,includeProperties:"ApplicationUser"),
                cartList = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == userId, includeProperties: "MenuItem").ToList(),
            };

            if (summaryViewModel.Address == null)
            {
                return RedirectToAction("UpsertAddress");
            }

            foreach (ShoppingCart cartItem in summaryViewModel.cartList)
            {
                summaryViewModel.OrderHeader.OrderTotal += (cartItem.MenuItem.Price * cartItem.Count);
            }

            
            summaryViewModel.OrderHeader.OrderDate = DateTime.Now.Date;
            summaryViewModel.OrderHeader.PickupName = applicationUser.FullName;

            return View(summaryViewModel);

        }


        public IActionResult ViewAddress()
        {
            Addresstb address = _unitOfWork.Addresstb.Get(u => u.UserId == _userManager.GetUserId(User));
            ViewData["Message"] = TempData["Message"] as String;

            return View("Address/ViewAddress", address);
        }

        public IActionResult UpsertAddress()
        {
            Addresstb address = _unitOfWork.Addresstb.Get(u => u.UserId == _userManager.GetUserId(User), includeProperties: "ApplicationUser");
            if (address == null)
            {
                address = new Addresstb();
                address.ApplicationUser = _userManager.GetUserAsync(User).Result;
                address.UserId = _userManager.GetUserId(User);
            }
            return View("Address/Upsert",address);
        }

        [HttpPost]
        public IActionResult UpSertAddress()
        {
            Addresstb address = _unitOfWork.Addresstb.Get(u => u.UserId == _userManager.GetUserId(User), includeProperties: "ApplicationUser");
            if (address == null)
            {
                address = new Addresstb();
                address.ApplicationUser = _userManager.GetUserAsync(User).Result;
            }

            address.Address = Request.Form["Address"];
            address.City = Request.Form["City"];
            address.Pincode = Request.Form["Pincode"];
            address.UserId = Request.Form["UserId"];

            ModelState.Clear();
            TryValidateModel(address,nameof(address));

            if (ModelState.IsValid)
            {
                Addresstb addressFromDb = _unitOfWork.Addresstb.Get(u => u.UserId == _userManager.GetUserId(User), includeProperties: "ApplicationUser");
                if (addressFromDb == null)
                {
                    address.UserId = _userManager.GetUserId(User);
                    _unitOfWork.Addresstb.Add(address);
                    TempData["Message"] = "Address added successfully";

                }
                else
                {
                    addressFromDb.Address = address.Address;
                    addressFromDb.City = address.City;
                    addressFromDb.Pincode = address.Pincode;
                    _unitOfWork.Addresstb.Update(addressFromDb);
                    TempData["Message"] = "Address updated successfully";

                }
                _unitOfWork.Save();
                return RedirectToAction("ViewAddress");
            }

            return View("Address/Upsert", address);
        }
    }
}

Restuarant_Management_System_IDP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - Food Bytes</title>
    <!-- CSS Files -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link href="~/css/jquery-ui.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Restuarant_Management_System_IDP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/2.2.1/css/dataTables.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    <!--Checking -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

</head>
<body class="search-background fs-5">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark fixed-top border-bottom box-shadow mb-3 py-3 px-5 fs-4">
            <div class="container-fluid">
                @if(User.IsInRole(SD.Admin)){
                    <a class="navbar-brand fs-4" asp-controller="Admin" asp-action="Dashboard">Food Bytes</a> 
                }
                else{
                    <a class="navbar-brand fs-4" asp-area="" asp-controller="Home" asp-action="Index">Food Bytes</a>
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white-50" asp-controller="Home" asp-action="Menu">Menu</a>
                        </li>
                        @if(User.IsInRole(SD.Customer)){
                            <li class="nav-item">
                                <a class="nav-link text-white-50" asp-controller="Order" asp-action="OrderHistory">Order History</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Admin)){

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="manageMenuDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Manage Menu
                                </a>
                                <div class="dropdown-menu" aria-labelledby="manageMenuDropdown">
                                    <a class="dropdown-item" asp-action="Category" asp-controller="ManageMenu">Category</a>
                                    <a class="dropdown-item" asp-action="SubCategory" asp-controller="ManageMenu">Sub Category</a>
                                    <a class="dropdown-item" asp-action="MenuItem" asp-controller="ManageMenu">MenuItem</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white-50" asp-controller="Admin" asp-action="GetUsers">Manage Users</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="manageOrderDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Order Manage
                                </a>
                                <div class="dropdown-menu" aria-labelledby="manageOrderDropdown">
                                    <a class="dropdown-item" asp-action="ManageOrder" asp-controller="Order">Manage Order</a>
                                    <a class="dropdown-item" asp-action="OrderPickup" asp-controller="Order">Order Delivery</a>
                                </div>
                            </li>
                        }
                        @if(User.IsInRole(SD.Kitchen) || User.IsInRole(SD.Delivery)){
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropDown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Order
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropDown">
                                    @if (User.IsInRole(SD.Kitchen))
                                    {
                                        <a class="dropdown-item" asp-action="ManageOrder" asp-controller="Order">Manage Order</a>
                                    }
                                    @if (User.IsInRole(SD.Delivery))
                                    {
                                        <a class="dropdown-item" asp-action="OrderPickup" asp-controller="Order">Order Pickup</a>
                                    }
                                </div>

                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link text-white-50" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if(User.IsInRole(SD.Customer)){
                            
                            string cartCount = httpContextAccessor.HttpContext.Session.GetString(SD.ShoppingCartCount);
                            cartCount = cartCount == "0" ? "" : cartCount;
                            
                            <li class="nav-item">
                                <a class="nav-link text-white-50" asp-controller="Customer" asp-action="Cart"><i class="bi bi-cart"></i> Cart <sup>@cartCount</sup></a>
                            </li>
                        }

                    </ul>

                    @* Add login partial view to display user name*@
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <br /><br /><br />
            @RenderBody()
        </main>
    </div>
    <br />
    <br />
    <br />
    <footer class="border-top pl-3 py-2 footer text-white-50" style="background-color:#343a40">
        <div class="container">
            &copy; 2025 - Restuarant_Management_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!-- JavaScript Files -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/2.2.1/js/dataTables.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Restuarant_Management_System_IDP/Views/Shared/_Notification.cshtml
@if (ViewData["Message"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        
        toastr.options = {
            "closeButton": true,
            "progressBar": true,
            "preventDuplicates": true,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "5000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "hideMethod": "fadeOut"
        };

        toastr.success('@ViewData["Message"]');
    </script>
}

Restuarant_Management_System_IDP/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}